# Generated by Django 3.2.4 on 2021-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrondissement',
            name='code',
            field=models.CharField(default=0, max_length=10, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
