# Generated by Django 3.2.4 on 2021-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210606_1345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plage',
            unique_together=set(),
        ),
    ]
