# Generated by Django 3.2.2 on 2021-06-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210605_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plage',
            name='date_debut',
            field=models.CharField(max_length=10, verbose_name='Date debut'),
        ),
        migrations.AlterField(
            model_name='plage',
            name='date_fin',
            field=models.CharField(max_length=10, verbose_name='Date fin'),
        ),
    ]
