# Generated by Django 3.2.2 on 2021-06-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210605_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plage',
            old_name='date_debut',
            new_name='horaire_debut',
        ),
    ]
