# Generated by Django 3.2.2 on 2021-06-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_fin_plage_horaire_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plage',
            name='horaire_debut',
            field=models.CharField(max_length=10, verbose_name='heure debut'),
        ),
        migrations.AlterField(
            model_name='plage',
            name='horaire_fin',
            field=models.CharField(max_length=10, verbose_name='heure fin'),
        ),
    ]
